config/routes.rb
Rails.application.routes.draw do

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  get '/signup', to: 'users#new'

  root 'static_pages#home'
  get '/about',  to: 'static_pages#about'

  resources :articles

  resources :articles do
    resources :comments,  only:[:create, :destroy]
  end

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 150 }
  validates :content, presence: true, length: { maximum: 30000 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only: [:new]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def index
    @articles = Article.paginate(page: params[:page])
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article created!"
      redirect_to article_url(@article)
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:success] = "Profile updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Article deleted"
    redirect_to user_url(current_user)
  end

  private
    def article_params
      params.require(:article).permit(:title, :content)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = Article.find(params[:id]).user
      redirect_to(root_url) unless (current_user?(@user) || current_user.admin == 1)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code="hello world", language)
      if language.nil?
        language = :c
      end
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :autolink => true,
        :strikethrough => true,
        :lax_html_blocks => true,
        :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/articles/_article.html.erb
<li id="article-<%= article.id %>">
  <%= link_to gravatar_for(article.user, size: 80), article.user %>
  <span class="user">
    <%= link_to article.user do %>
        <h4><%= article.user.name %></h4>
    <% end %>
  </span>
  <span class="content">
    <%= link_to article_url(article.id) do %>
        <h2><%= article.title %></h2>
    <% end %>
  </span>
  <% if (current_user == article.user || (logged_in? && current_user.admin == 1)) %>
    <span>
      <%= link_to 'Edit', edit_article_path(article) %>
    </span>
      |
    <span>
      <%= link_to 'Delete', article_path(article.id), method: :delete,
                  data: { confirm: "You sure?"} %>
    </span>
  <% end %>
  <span class="text-left">
    Posted <%= time_ago_in_words(article.created_at) %> ago.
  </span>

</li>

app/views/articles/_error.html.erb
<% if @article.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@article.errors.count, "error") %>.
      </div>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, 'Update Article') %>
<%= form_for(@article) do |f| %>
    <%= render 'error' %>

    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: "50" %>

    <%= f.submit "Commit the article", class: "btn btn-primary" %>
<% end %>

app/views/articles/index.html.erb
<%= provide(:title, "Articles") %>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <% if @articles.any? %>
        <h3>articles (<%= Article.count %>)</h3>
        <ol class="articles">
          <%= render @articles %>
        </ol>
        <%= will_paginate @articles %>
    <% end %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'Write Article') %>
<%= form_for(@article) do |f| %>
    <%= render 'error' %>

    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: "50" %>

    <%= f.submit "Commit the article", class: "btn btn-primary" %>
<% end %>

app/views/articles/show.html.erb
<%= provide(:title, @article.title) %>
<div class="page-header">
  <h1 class="text-center">
    <strong>
      <%= @article.title %>
    </strong>
  </h1>

  <div class="container" color="grey">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <h4 class="text-right">
          <strong>
            <%= link_to @article.user.name, @article.user %>
          </strong> |
          <em>
            <%= @article.created_at %>
          </em>
        </h4>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="well-lg">
    <%= markdown @article.content %>
  </div>
</div>

<% if @article.comments.any? %>
  <div class="panel panel-default">
    <div class="well-lg">
      <h2> Comments:</h2>
      <% @article.comments.each do |comment| %>
        <HR style="FILTER: alpha(opacity=100,finishopacity=0,style=3)" width="80%" SIZE=3>
        <div class="container">
          <div class="row clearfix">
            <div class="col-md-1 column">
              <%= link_to gravatar_for(comment.user, size: 80), comment.user %>
            </div>
            <div class="col-md-10 column">
              <h5>
                <%= link_to comment.user.name, comment.user %>
              </h5>
              <%= comment.content %>
                <% if logged_in? && current_user.admin == 1 || current_user?(comment.user) %>
                  <br>
                  <div class="text-right">
                    <%= link_to "delete", article_comment_url(comment.article_id, comment.id), method: :delete,
                                                                                        data: { confirm: "You sure?"} %>
                  </div>
                  <% else %>
                    <br>
                    <br>
                    <% end %>
                      <br>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <% end %>


    <div class="well-lg">
      <% if logged_in? %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              Add a comment:
            </h3>
          </div>
          <div class="panel-body">
            <%= form_for([@article, @article.comments.build]) do |f| %>
              <p>
                <%= f.text_area :content, class: "form-control" %>
              </p>
              <p>
                <%= f.submit class: "btn btn-primary" %>
              </p>
              <% end %>
          </div>
        </div>

        <% end %>
    </div>