config/routes.rb
Rails.application.routes.draw do

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  get '/signup', to: 'users#new'

  root 'static_pages#home'
  get '/about',  to: 'static_pages#about'

  resources :articles

  resources :articles do
    resources :comments,  only:[:create, :destroy]
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row" >
    <div class="col-md-10">
      <small>© 2018 cyyzero All rights reserved.</small>
      <nav>
        <ul>
          <small>Powered by rails</small>
          <%= link_to image_tag("rails.png", alt: "Rails logo", size: "20x30"),
                  'http://rubyonrails.org/' %>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
      data-target="#example-navbar-collapse">
        <span class="sr-only">切换导航</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BNB", root_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="example-navbar-collapse">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Articles",articles_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Write', new_article_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Setting', edit_user_path(current_user) %></li>
              <li class="'divider"></li>
              <li>
                <%= link_to 'Log out', logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <%end%>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>